### PR TITLE
FINCN-164: Dockerize fims web app with adjustments to make it work with docker-compose

### PR DESCRIPTION
**Pull request by aasaru**
## Description

Built on https://github.com/apache/fineract-cn-fims-web-app/pull/18
and replaced localhost with service names so it would work with other services in docker-compose scripts. I tested and added to docker-compose scripts here:
https://github.com/apache/fineract-cn-docker-compose/pull/2
(currently it is from my own Docker Hub repo as the official repo has not been created yet)

### CODE REVIEW

**Comment by awasum** [comment]
Create a different nginx file in the script folder which contains the the docker containers as hosts.
Something like docker.nginx.conf, then on this line: https://github.com/apache/fineract-cn-fims-web-app/pull/20/commits/b097ba1c34237e31f71d73c30b2492d151b67c73#diff-3254677a7917c6c01f55212f86c57fbfR21

copy that docker specific nginx conf into the nginx container.

Not everyone will host fims in a docker container..Some will use a good old fashion host so I prefer you keep that default localhost example.

Why did you not merge #18 before working on this?

**Comment by awasum** [comment]
Just merged #18

**Comment by aasaru** [comment]
I don't have merge rights on any apache/fineract-cn-* repo.

**Comment by awasum** [comment]
Pull and fix this PR wrt to the feedback above..if its Ok with you.

**Comment by awasum** [comment]
Why dont you have permission? You are a committer.

See here: https://cwiki.apache.org/confluence/display/FINERACT/Working+with+gitbox+to+contribute+to+Apache+Fineract+CN

do you have permission to read.write Fineract 1.x repo?

**Comment by aasaru** [comment]
yeah. I had impression that nginx is only used for docker so yes, I need to fix this.

**Comment by aasaru** [comment]
Thanks for the instructions, I wasn't aware of this. I thought there is some level #2 of commiters who have right to accept pull requests :-)

**Comment by aasaru** [comment]
I now pushed the changes you suggested @awasum . 
I set up everything here: https://cwiki.apache.org/confluence/display/FINERACT/Working+with+gitbox+to+contribute+to+Apache+Fineract+CN but I still don't see any merge button. I don't think I have write rights to Fineract 1.x repo.

**Comment by aasaru** [comment]
@awasum any chanche you could review this again?

**Comment by aasaru** [comment]
I can now merge pull requests, so that one is now solved. I will merge this PR in 24h if anyone doesn't object.

**Comment by awasum** [comment]
Go ahead.

**Pull request merged**
