### PR TITLE
Fixing the issue FINCN-101:Group Definition Minimum and Maximum Numbe…

### PR DESCRIPTION
**Pull request by kengneruphine**
…rs should not be decimals

## Description
- Created a custom number-input property called number-group-input which set "requireDecimals" to false to be used for the group service since it does not require decimals number.
- Removed Group from the Quick-access page which when clicked at first let to an error message of not having the required permission.
- Made changes in the package.json file for npm run build to compile successful

### What's included?

- One
- Two
- Three

#### Test Steps

- [ ] do this
- [ ] then this
- [ ] finally this

##### Screenshots or link to CodePen/Plunker/JSfiddle

### CODE REVIEW

**Comment by cabrelkemfang** [comment]
When i run "npm run test" I have this error 
screenshot from 2018-10-20 11-28-45

**Comment by kengneruphine** [comment]
@cabrelkemfang ,
This error is generated by the unit test for the Group service which I started writing.
 I already created an issue https://issues.apache.org/jira/browse/FINCN-100, which is writing unit test for the Group service into fims.
Let me finish writing the unit test and after that I will send another commit

**Comment by cabrelkemfang** [comment]
@kengneruphine  Can you please look at this 
screenshot from 2018-10-20 13-05-06

**Comment by awasum** [comment]
Close and Reopen to trigger Travis build.

**Comment by awasum** [comment]
If you pull #17   and put ontop of this...then npm run tslint will pass and wat will be left is testing and building which are stillthrowing errors in Travis.

**Comment by awasum** [comment]
@kengneruphine  Conflicts?

**Comment by awasum** [comment]
https://github.com/apache/fineract-cn-fims-web-app/pull/12/conflicts

**Comment by awasum** [comment]
Travis is not picking up?

**Comment by awasum** [comment]
@cabrelkemfang @markvanveen Please take some time to look at this problem when we run `npm run test` on this PR.
Its blocking progress from been made here.
We really need help with this. https://travis-ci.com/apache/fineract-cn-fims-web-app/builds/118325684

**Comment by crain** [comment]
If you add --sm=false to the test script in package.json like:

`"test": "ng test --single-run --sm=false"`

It will run through and show you the correct error messages. I see the following:

> ERROR: 'ERROR', TypeError: Cannot read property 'nativeElement' of undefined
TypeError: Cannot read property 'nativeElement' of undefined
    at MatSelect._onFadeInDone (webpack:///./node_modules/@angular/material/esm5/select.es5.js?:778:20)
    at Object.eval [as handleEvent] (ng:///MatSelectModule/MatSelect.ngfactory.js:70:27)
    at handleEvent (webpack:///./node_modules/@angular/core/@angular/core.es5.js?:12198:138)
    at callWithDebugContext (webpack:///./node_modules/@angular/core/@angular/core.es5.js?:13667:42)
    at Object.debugHandleEvent [as handleEvent] (webpack:///./node_modules/@angular/core/@angular/core.es5.js?:13255:12)
    at dispatchEvent (webpack:///./node_modules/@angular/core/@angular/core.es5.js?:8814:21)
    at eval (webpack:///./node_modules/@angular/core/@angular/core.es5.js?:9428:20)
    at eval (webpack:///./node_modules/@angular/platform-browser/@angular/platform-browser/animations.es5.js?:303:25)
    at Array.forEach (<anonymous>)

Why sm=false? See here https://github.com/angular/angular-cli/issues/7296

Unfortunately the test is green altough its clearly showing an error and I can't see on which test its failing. May be you could debug a bit further?

**Comment by aasaru** [comment]
I took https://github.com/apache/fineract-cn-fims-web-app/pull/12#issuecomment-510483296 suggestoin and created a pull request to fix this build: https://github.com/kengneruphine/fineract-cn-fims-web-app/pull/1

**Comment by awasum** [comment]
Closing this in favour of merging this new one: https://github.com/apache/fineract-cn-fims-web-app/pull/19

**Comment by awasum** [comment]
@markvanveen  Thanks for the help. See #19  which incorporates your suggestion.

**Pull request closed without merging**
