### PR TITLE
FINCN-168: Fix tslint to make Travis CI pass

### PR DESCRIPTION
**Pull request by awasum**
First stage to make travis builds to begin passing again.
Next sub task is to make the unit tests to run and the npm builds to work.

### CODE REVIEW

**Comment by awasum** [comment]
"npm run tslint" now passing but tests and builds are still failing.
Seems there is a problem with Group tests...
Could be linked to this PR: #12

**Comment by kengneruphine** [comment]
Hey @awasum , The error is not in the with the Group test. It is from the Teller service from the available-actions.service.spec.ts file line 68

**Comment by awasum** [comment]
Do you know how we can fix it @kengneruphine ?

**Comment by awasum** [comment]
Travis build failure logs:https://travis-ci.com/apache/fineract-cn-fims-web-app/builds/118153337

**Comment by kengneruphine** [comment]
@awasum, from the travis log, I see errors about Group Unit tests. If you pull the commits from the PR: #12 , It will resolves those errors

**Comment by awasum** [comment]
This is giving me merge conlicts..If you have it already on ur local setup..send a new PR to fix this and I will close this one

**Comment by awasum** [comment]
Maybe you add a new commit under #12  fixing the tslint...

**Comment by kengneruphine** [comment]
Yeah,I will send the commit

**Comment by awasum** [comment]
This is no longer necessary as its handled in https://github.com/apache/fineract-cn-fims-web-app/pull/19
SO am closing.

**Pull request closed without merging**
