### PR TITLE
Compilation error

### PR DESCRIPTION
**Pull request by vigyat123**
## Description

Variable not defined and a variable spelled incorrectly. Component not defined in common.module.ts file

### What's included?

- "lastModifiedBy" spelled incorrectly in "src/app/services/group/domain/group.model.ts"
- "applicationDate?: string;" added in "src/app/services/group/domain/group.model.ts"
- Added "GroupSelectComponent" in imports and exports in NgModule in "fineract-cn-fims-web-app/src/app/common/common.module.ts"
#### Test Steps

- Pull
- npm i
- npm run dev

##### Screenshots or link to CodePen/Plunker/JSfiddle
error

### CODE REVIEW

**Comment by awasum** [comment]
image

@vigyat123 There is the above error I get when I run 'npm run dev'. It seems merging an earlier commit from @kengneruphine has fixed some of the problems and this PR might no longer be necessary.
Please pull the latest changes from develop branch and test again. Then let me know if we need to close this one and you send another PR.

Thanks.

**Comment by karthyk16** [comment]
@awasum @kengneruphine  : We took the dev branch and ran the prod build command which is failing for Error in UglifyJS

PFB the screenshot of the error.

ui_build_error

Can you help us if you are also getting this issue.?

**Comment by awasum** [comment]
@kengneruphine , Please can you help look into this issue?

@karthyk16  What version of node and npm are you using? Also create an issue on Fineract CN JIRA for this issue please.

**Comment by karthyk16** [comment]
@awasum  @kengneruphine  : NPM 6.4.1 and Node 8.11.3

**Comment by QiangZhu** [comment]
My issue is as the same as Karthyk16 using Node  8.10.0 and NPM 3.5.2 , and change it to  Node v10.11.0
 and NPM 6.4.1 , the result is the same. please help me, thanks. 

the building err information is : 

    ERROR in 10.bf4f22bf447fda294c62.chunk.js from UglifyJs
    TypeError: Cannot set property 'fixed' of undefined
    at TreeWalker.eval [as visit] (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:5584:25)
    at TreeWalker._visit (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1339:24)
    at AST_This._walk (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:480:24)
    at AST_Dot.eval (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1061:29)
    at TreeWalker._visit (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1343:21)
    at AST_Dot._walk (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1060:24)
    at AST_Dot.walk (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:483:21)
    at TreeWalker.eval [as visit] (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:5722:31)
    at TreeWalker._visit (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1339:24)
    at AST_ForIn._walk (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:653:24)
    at walk_body (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:530:17)
    at AST_Function.eval (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:771:13)
    at eval (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1340:21)
    at TreeWalker.eval [as visit] (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:5665:21)
    at TreeWalker._visit (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1339:24)
    at AST_Function._walk (eval at <anonymous> (/home/ubuntu/github/integratoin-tests/fineract-cn-fims-web-app/node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:765:24)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! fims@0.1.0 build: `ng build --prod`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the fims@0.1.0 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by awasum** [comment]
Hey @QiangZhu ,

Create an issue here: https://issues.apache.org/jira/projects/FINCN/issues/
Join the mailing list by sending a blank mail to :  dev-subscribe@fineract.apache.org 

Also see our website: https://fineract.apache.org/

**Comment by kengneruphine** [comment]
Hey @QiangZhu , @karthyk16 ,

 I am working on the issue

**Comment by karthyk16** [comment]
@kengneruphine  : Thank You. Looking forward for the fix.

**Comment by awasum** [comment]
I think the issue here has been fixed by: https://github.com/apache/fineract-cn-fims-web-app/pull/13

Pull again @vigyat123 and @karthyk16 , test and let us know.

**Comment by awasum** [comment]
Already fixed: https://github.com/apache/fineract-cn-fims-web-app/pull/13

So closing.

**Pull request closed without merging**
